CREATE TABLE terminals (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  login TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tickets (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  pin INTEGER NOT NULL,
  amount INTEGER NOT NULL,
  status TEXT DEFAULT 'NEW',
  attempts INTEGER DEFAULT 0,
  terminal_id INTEGER NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (terminal_id) REFERENCES terminals(id)
);
